





[annotator]

    [annotator.NamedEntityAnnotator] ## ner is the key for this annotator to get all the variables
    annotator_class ="cag.graph_framework.components.annotators.instance.ner_annotator.NamedEntityAnnotator"
    pipe = "ner"
    pipe_path = "" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or set
    type = "text" # for now we support text - later url, image
    annotated_column="text"
    input_id = "id"

    [annotator.EmpathAnnotator] ## Spacy customized
    annotator_class ="textmining.annotators.instance.empath_annotator.EmpathAnnotator"
    pipe = "empath_component"
    pipe_path = "cag.graph_framework.components.annotators.pipe.linguistic.style_features" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or corpus
    type = "text" # for now we support text - later url, image
    annotated_column="text"

    [annotator.DummyDefaultAnnotator] ## ner is the key for this annotator to get all the variables
    annotator_class ="cag.graph_framework.components.annotators.instance.dummy.DummyDefaultAnnotator"
    vertex_class = "cag.graph_framework.graph.nodes.GenericNode"
    edge_class = "cag.graph_framework.components.annotators.element.graph_elements.HasAnnotation"
    pipe = "customized_pipe_func" # for spacy pipe name, for
    pipe_path = "cag.graph_framework.components.annotators.instance.dummy" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or corpus
    type = "text" # for now we support text - later url, image
    annotated_column="text"


## TO ADD AN Annotator, add the following entries as above with the exact indetation



